//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerialShell.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int connectionbaud {
            get {
                return ((int)(this["connectionbaud"]));
            }
            set {
                this["connectionbaud"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool connectiondatasize {
            get {
                return ((bool)(this["connectiondatasize"]));
            }
            set {
                this["connectiondatasize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int connectionstopbits {
            get {
                return ((int)(this["connectionstopbits"]));
            }
            set {
                this["connectionstopbits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int connectionparity {
            get {
                return ((int)(this["connectionparity"]));
            }
            set {
                this["connectionparity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int senddatatype {
            get {
                return ((int)(this["senddatatype"]));
            }
            set {
                this["senddatatype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int sendlineending {
            get {
                return ((int)(this["sendlineending"]));
            }
            set {
                this["sendlineending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string sendsendfilepath {
            get {
                return ((string)(this["sendsendfilepath"]));
            }
            set {
                this["sendsendfilepath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int receivedatatype {
            get {
                return ((int)(this["receivedatatype"]));
            }
            set {
                this["receivedatatype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string receivelogpath {
            get {
                return ((string)(this["receivelogpath"]));
            }
            set {
                this["receivelogpath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool receivelogpathCheckBox {
            get {
                return ((bool)(this["receivelogpathCheckBox"]));
            }
            set {
                this["receivelogpathCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroColorStyle metrostyle {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["metrostyle"]));
            }
            set {
                this["metrostyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public global::MetroFramework.MetroThemeStyle metrotheme {
            get {
                return ((global::MetroFramework.MetroThemeStyle)(this["metrotheme"]));
            }
            set {
                this["metrotheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickButton1_Type {
            get {
                return ((string)(this["shortcutJoystickButton1_Type"]));
            }
            set {
                this["shortcutJoystickButton1_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickButton1_Repeat {
            get {
                return ((string)(this["shortcutJoystickButton1_Repeat"]));
            }
            set {
                this["shortcutJoystickButton1_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickButton1_Data {
            get {
                return ((string)(this["shortcutJoystickButton1_Data"]));
            }
            set {
                this["shortcutJoystickButton1_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickButton2_Type {
            get {
                return ((string)(this["shortcutJoystickButton2_Type"]));
            }
            set {
                this["shortcutJoystickButton2_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickButton2_Repeat {
            get {
                return ((string)(this["shortcutJoystickButton2_Repeat"]));
            }
            set {
                this["shortcutJoystickButton2_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickButton2_Data {
            get {
                return ((string)(this["shortcutJoystickButton2_Data"]));
            }
            set {
                this["shortcutJoystickButton2_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickButton3_Type {
            get {
                return ((string)(this["shortcutJoystickButton3_Type"]));
            }
            set {
                this["shortcutJoystickButton3_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickButton3_Repeat {
            get {
                return ((string)(this["shortcutJoystickButton3_Repeat"]));
            }
            set {
                this["shortcutJoystickButton3_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickButton3_Data {
            get {
                return ((string)(this["shortcutJoystickButton3_Data"]));
            }
            set {
                this["shortcutJoystickButton3_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickButton4_Type {
            get {
                return ((string)(this["shortcutJoystickButton4_Type"]));
            }
            set {
                this["shortcutJoystickButton4_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickButton4_Repeat {
            get {
                return ((string)(this["shortcutJoystickButton4_Repeat"]));
            }
            set {
                this["shortcutJoystickButton4_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickButton4_Data {
            get {
                return ((string)(this["shortcutJoystickButton4_Data"]));
            }
            set {
                this["shortcutJoystickButton4_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickL1_Type {
            get {
                return ((string)(this["shortcutJoystickL1_Type"]));
            }
            set {
                this["shortcutJoystickL1_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickL1_Repeat {
            get {
                return ((string)(this["shortcutJoystickL1_Repeat"]));
            }
            set {
                this["shortcutJoystickL1_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickL1_Data {
            get {
                return ((string)(this["shortcutJoystickL1_Data"]));
            }
            set {
                this["shortcutJoystickL1_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickL2_Type {
            get {
                return ((string)(this["shortcutJoystickL2_Type"]));
            }
            set {
                this["shortcutJoystickL2_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickL2_Repeat {
            get {
                return ((string)(this["shortcutJoystickL2_Repeat"]));
            }
            set {
                this["shortcutJoystickL2_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickL2_Data {
            get {
                return ((string)(this["shortcutJoystickL2_Data"]));
            }
            set {
                this["shortcutJoystickL2_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickL3_Type {
            get {
                return ((string)(this["shortcutJoystickL3_Type"]));
            }
            set {
                this["shortcutJoystickL3_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickL3_Repeat {
            get {
                return ((string)(this["shortcutJoystickL3_Repeat"]));
            }
            set {
                this["shortcutJoystickL3_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickL3_Data {
            get {
                return ((string)(this["shortcutJoystickL3_Data"]));
            }
            set {
                this["shortcutJoystickL3_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickR1_Type {
            get {
                return ((string)(this["shortcutJoystickR1_Type"]));
            }
            set {
                this["shortcutJoystickR1_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickR1_Repeat {
            get {
                return ((string)(this["shortcutJoystickR1_Repeat"]));
            }
            set {
                this["shortcutJoystickR1_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickR1_Data {
            get {
                return ((string)(this["shortcutJoystickR1_Data"]));
            }
            set {
                this["shortcutJoystickR1_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickR2_Type {
            get {
                return ((string)(this["shortcutJoystickR2_Type"]));
            }
            set {
                this["shortcutJoystickR2_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickR2_Repeat {
            get {
                return ((string)(this["shortcutJoystickR2_Repeat"]));
            }
            set {
                this["shortcutJoystickR2_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickR2_Data {
            get {
                return ((string)(this["shortcutJoystickR2_Data"]));
            }
            set {
                this["shortcutJoystickR2_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickR3_Type {
            get {
                return ((string)(this["shortcutJoystickR3_Type"]));
            }
            set {
                this["shortcutJoystickR3_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickR3_Repeat {
            get {
                return ((string)(this["shortcutJoystickR3_Repeat"]));
            }
            set {
                this["shortcutJoystickR3_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickR3_Data {
            get {
                return ((string)(this["shortcutJoystickR3_Data"]));
            }
            set {
                this["shortcutJoystickR3_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickUp_Type {
            get {
                return ((string)(this["shortcutJoystickUp_Type"]));
            }
            set {
                this["shortcutJoystickUp_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickUp_Repeat {
            get {
                return ((string)(this["shortcutJoystickUp_Repeat"]));
            }
            set {
                this["shortcutJoystickUp_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickUp_Data {
            get {
                return ((string)(this["shortcutJoystickUp_Data"]));
            }
            set {
                this["shortcutJoystickUp_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickDown_Type {
            get {
                return ((string)(this["shortcutJoystickDown_Type"]));
            }
            set {
                this["shortcutJoystickDown_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickDown_Repeat {
            get {
                return ((string)(this["shortcutJoystickDown_Repeat"]));
            }
            set {
                this["shortcutJoystickDown_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickDown_Data {
            get {
                return ((string)(this["shortcutJoystickDown_Data"]));
            }
            set {
                this["shortcutJoystickDown_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickLeft_Type {
            get {
                return ((string)(this["shortcutJoystickLeft_Type"]));
            }
            set {
                this["shortcutJoystickLeft_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickLeft_Repeat {
            get {
                return ((string)(this["shortcutJoystickLeft_Repeat"]));
            }
            set {
                this["shortcutJoystickLeft_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickLeft_Data {
            get {
                return ((string)(this["shortcutJoystickLeft_Data"]));
            }
            set {
                this["shortcutJoystickLeft_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickRight_Type {
            get {
                return ((string)(this["shortcutJoystickRight_Type"]));
            }
            set {
                this["shortcutJoystickRight_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickRight_Repeat {
            get {
                return ((string)(this["shortcutJoystickRight_Repeat"]));
            }
            set {
                this["shortcutJoystickRight_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickRight_Data {
            get {
                return ((string)(this["shortcutJoystickRight_Data"]));
            }
            set {
                this["shortcutJoystickRight_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickStart_Type {
            get {
                return ((string)(this["shortcutJoystickStart_Type"]));
            }
            set {
                this["shortcutJoystickStart_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickStart_Repeat {
            get {
                return ((string)(this["shortcutJoystickStart_Repeat"]));
            }
            set {
                this["shortcutJoystickStart_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickStart_Data {
            get {
                return ((string)(this["shortcutJoystickStart_Data"]));
            }
            set {
                this["shortcutJoystickStart_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutJoystickSelect_Type {
            get {
                return ((string)(this["shortcutJoystickSelect_Type"]));
            }
            set {
                this["shortcutJoystickSelect_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutJoystickSelect_Repeat {
            get {
                return ((string)(this["shortcutJoystickSelect_Repeat"]));
            }
            set {
                this["shortcutJoystickSelect_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickSelect_Data {
            get {
                return ((string)(this["shortcutJoystickSelect_Data"]));
            }
            set {
                this["shortcutJoystickSelect_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl0_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl0_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl0_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl0_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl0_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl0_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl0_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl0_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl0_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl1_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl1_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl1_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl1_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl1_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl1_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl1_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl1_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl1_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl2_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl2_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl2_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl2_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl2_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl2_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl2_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl2_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl2_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl3_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl3_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl3_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl3_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl3_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl3_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl3_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl3_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl3_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl4_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl4_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl4_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl4_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl4_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl4_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl4_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl4_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl4_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl5_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl5_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl5_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl5_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl5_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl5_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl5_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl5_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl5_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl6_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl6_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl6_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl6_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl6_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl6_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl6_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl6_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl6_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl7_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl7_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl7_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl7_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl7_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl7_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl7_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl7_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl7_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl8_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl8_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl8_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl8_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl8_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl8_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl8_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl8_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl8_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("string")]
        public string shortcutKeyboardCtrl9_Type {
            get {
                return ((string)(this["shortcutKeyboardCtrl9_Type"]));
            }
            set {
                this["shortcutKeyboardCtrl9_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string shortcutKeyboardCtrl9_Repeat {
            get {
                return ((string)(this["shortcutKeyboardCtrl9_Repeat"]));
            }
            set {
                this["shortcutKeyboardCtrl9_Repeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl9_Data {
            get {
                return ((string)(this["shortcutKeyboardCtrl9_Data"]));
            }
            set {
                this["shortcutKeyboardCtrl9_Data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickButton1_DataRelease {
            get {
                return ((string)(this["shortcutJoystickButton1_DataRelease"]));
            }
            set {
                this["shortcutJoystickButton1_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickButton2_DataRelease {
            get {
                return ((string)(this["shortcutJoystickButton2_DataRelease"]));
            }
            set {
                this["shortcutJoystickButton2_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickButton3_DataRelease {
            get {
                return ((string)(this["shortcutJoystickButton3_DataRelease"]));
            }
            set {
                this["shortcutJoystickButton3_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickButton4_DataRelease {
            get {
                return ((string)(this["shortcutJoystickButton4_DataRelease"]));
            }
            set {
                this["shortcutJoystickButton4_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickL1_DataRelease {
            get {
                return ((string)(this["shortcutJoystickL1_DataRelease"]));
            }
            set {
                this["shortcutJoystickL1_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickL2_DataRelease {
            get {
                return ((string)(this["shortcutJoystickL2_DataRelease"]));
            }
            set {
                this["shortcutJoystickL2_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickL3_DataRelease {
            get {
                return ((string)(this["shortcutJoystickL3_DataRelease"]));
            }
            set {
                this["shortcutJoystickL3_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickR1_DataRelease {
            get {
                return ((string)(this["shortcutJoystickR1_DataRelease"]));
            }
            set {
                this["shortcutJoystickR1_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickR2_DataRelease {
            get {
                return ((string)(this["shortcutJoystickR2_DataRelease"]));
            }
            set {
                this["shortcutJoystickR2_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickR3_DataRelease {
            get {
                return ((string)(this["shortcutJoystickR3_DataRelease"]));
            }
            set {
                this["shortcutJoystickR3_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickStart_DataRelease {
            get {
                return ((string)(this["shortcutJoystickStart_DataRelease"]));
            }
            set {
                this["shortcutJoystickStart_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickSelect_DataRelease {
            get {
                return ((string)(this["shortcutJoystickSelect_DataRelease"]));
            }
            set {
                this["shortcutJoystickSelect_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickLeft_DataRelease {
            get {
                return ((string)(this["shortcutJoystickLeft_DataRelease"]));
            }
            set {
                this["shortcutJoystickLeft_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickRight_DataRelease {
            get {
                return ((string)(this["shortcutJoystickRight_DataRelease"]));
            }
            set {
                this["shortcutJoystickRight_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickUp_DataRelease {
            get {
                return ((string)(this["shortcutJoystickUp_DataRelease"]));
            }
            set {
                this["shortcutJoystickUp_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutJoystickDown_DataRelease {
            get {
                return ((string)(this["shortcutJoystickDown_DataRelease"]));
            }
            set {
                this["shortcutJoystickDown_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl0_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl0_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl0_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl1_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl1_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl1_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl2_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl2_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl2_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl3_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl3_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl3_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl4_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl4_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl4_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl5_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl5_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl5_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl6_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl6_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl6_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl7_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl7_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl7_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl8_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl8_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl8_DataRelease"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string shortcutKeyboardCtrl9_DataRelease {
            get {
                return ((string)(this["shortcutKeyboardCtrl9_DataRelease"]));
            }
            set {
                this["shortcutKeyboardCtrl9_DataRelease"] = value;
            }
        }
    }
}
